# Generated by Django 4.2.10 on 2024-02-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0006_remove_reception_prescription"),
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("diagnosis", models.TextField()),
                ("medication", models.TextField()),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reception.reception",
                    ),
                ),
            ],
        ),
    ]
