# Generated by Django 4.2.10 on 2024-02-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_client_is_vip"),
        ("prescription", "0002_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.client",
            ),
        ),
    ]
