# Generated by Django 5.0 on 2024-05-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prescription",
            "0005_prescription_created_at_prescription_created_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("consumption_time", models.CharField(max_length=255)),
                ("consumption_dose", models.CharField(max_length=255)),
                ("how_to_use", models.CharField(max_length=255)),
                ("repeat_interval", models.CharField(max_length=255)),
                ("repeat_period", models.PositiveIntegerField()),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescription.prescription",
                    ),
                ),
            ],
        ),
    ]
