# Generated by Django 5.0 on 2024-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0008_alter_prescriptionitem_prescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="instructions",
        ),
        migrations.AddField(
            model_name="prescription",
            name="notes",
            field=models.TextField(default="this is test "),
            preserve_default=False,
        ),
    ]
