# Generated by Django 5.0 on 2024-05-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0010_prescription_jalali_date"),
        ("reception", "0022_reception_jalali_date_alter_reception_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="national_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="reception",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reception.reception",
            ),
        ),
    ]
