# Generated by Django 5.0 on 2024-05-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0012_temporaryprescription_name_and_more"),
        ("reception", "0022_reception_jalali_date_alter_reception_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="temporaryprescription",
            name="name",
        ),
        migrations.RemoveField(
            model_name="temporaryprescription",
            name="national_id",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="reception",
            field=models.ForeignKey(
                default= 1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reception.reception",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="temporaryprescription",
            name="reception",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reception.reception",
            ),
            preserve_default=False,
        ),
    ]
