# Generated by Django 4.2.10 on 2024-03-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctor_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
