# Generated by Django 4.2.10 on 2024-03-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_is_vip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_vip",
        ),
    ]
