# Generated by Django 4.2.10 on 2024-03-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_remove_doctor_is_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images"
            ),
        ),
    ]
