# Generated by Django 5.0 on 2024-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
