# Generated by Django 5.0 on 2024-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/images/default.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
