# Generated by Django 4.2.13 on 2024-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
    ]
