# Generated by Django 4.2.10 on 2024-03-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_service_recommendations_service_therapeutic_measures"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
