# Generated by Django 4.2.10 on 2024-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_service_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="appointment_per_day",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
