# Generated by Django 4.2.10 on 2024-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_service_off_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="off_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Sunday"),
                    (2, "Monday"),
                    (3, "Tuesday"),
                    (4, "Wednesday"),
                    (5, "Thursday"),
                    (6, "Friday"),
                    (7, "Saturday"),
                ],
                default=6,
            ),
        ),
    ]
