# Generated by Django 4.2.10 on 2024-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_alter_service_off_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="service",
            name="off_day",
        ),
        migrations.AddField(
            model_name="service",
            name="off_days",
            field=models.ManyToManyField(blank=True, to="services.offday"),
        ),
    ]
