# Generated by Django 4.2.10 on 2024-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_servicecategory_alter_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
