# Generated by Django 4.2.10 on 2024-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_alter_servicecategory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="equipment_supplies",
        ),
        migrations.RemoveField(
            model_name="service",
            name="notes",
        ),
    ]
