# Generated by Django 4.2.10 on 2024-03-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="package",
            name="preparation_instructions",
        ),
        migrations.RemoveField(
            model_name="package",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="package",
            name="services",
        ),
        migrations.RemoveField(
            model_name="package",
            name="therapeutic_measures",
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gap_with_next_service", models.PositiveIntegerField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.package",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
