# Generated by Django 4.2.10 on 2024-03-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_alter_servicepackage_gap_with_next_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicepackage",
            old_name="gap_with_next_service",
            new_name="gap_with_previous_service",
        ),
    ]
