# Generated by Django 4.2.10 on 2024-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0021_rename_gap_with_next_service_servicepackage_gap_with_previous_service",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepackage",
            name="gap_with_previous_service",
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="gap_with_next_service",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
