# Generated by Django 4.2.10 on 2024-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_package_preparation_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
        migrations.AddField(
            model_name="package",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
