# Generated by Django 4.2.10 on 2024-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0009_rename_medicalequipment_equipment"),
        ("services", "0024_package_attachment_package_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="medical_equipment",
            field=models.ManyToManyField(blank=True, null=True, to="asset.equipment"),
        ),
    ]
