# Generated by Django 4.2.10 on 2024-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0009_rename_medicalequipment_equipment"),
        ("services", "0025_service_medical_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="medical_equipment",
            field=models.ManyToManyField(blank=True, to="asset.equipment"),
        ),
    ]
