# Generated by Django 4.2.10 on 2024-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0026_alter_service_medical_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="doctor_wage_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
