# Generated by Django 4.2.10 on 2024-03-22 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0028_rename_doctor_wage_percentage_service_doctors_wage_percentage",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="doctors_wage_percentage",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
