# Generated by Django 4.2.11 on 2024-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_servicespecification"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="prepayment",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
