# Generated by Django 4.2.11 on 2024-03-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0031_package_prepayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="prepayment",
        ),
    ]
