# Generated by Django 5.0 on 2024-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0032_remove_package_prepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="check_consumable_inventory",
            field=models.BooleanField(default=True),
        ),
    ]
