# Generated by Django 5.0 on 2024-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0033_service_check_consumable_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="inventory_minimum_value",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
