# Generated by Django 5.0 on 2024-04-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_service_inventory_minimum_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="inventory_minimum_value",
        ),
    ]
