# Generated by Django 5.0 on 2024-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0037_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offday",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "شنبه"),
                    (2, "یک شنبه"),
                    (3, "دو شنبه"),
                    (4, "سه شنبه"),
                    (5, "چهارشنبه"),
                    (6, "پنج شنبه"),
                    (7, "جمعه"),
                ]
            ),
        ),
    ]
