# Generated by Django 5.0 on 2024-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        ("services", "0038_alter_offday_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="off_days",
            field=models.ManyToManyField(blank=True, to="planner.weekday"),
        ),
    ]
