# Generated by Django 5.0 on 2024-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0039_alter_service_off_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="off_days",
            field=models.ManyToManyField(blank=True, null=True, to="services.offday"),
        ),
    ]
