# Generated by Django 4.2.10 on 2024-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_packageappointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageappointment",
            name="status",
            field=models.CharField(
                choices=[("WAITE", "WAITE"), ("DONE", "DONE")],
                default="WAITE",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
