# Generated by Django 4.2.10 on 2024-03-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_appointment_status_alter_packageappointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="has_package",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.packageappointment",
            ),
        ),
    ]
