# Generated by Django 4.2.11 on 2024-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_appointment_created_at_appointment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageappointment",
            name="prepayment",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
