# Generated by Django 5.0 on 2024-04-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_packageappointment_prepayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="packageappointment",
            name="name",
        ),
    ]
