# Generated by Django 5.0 on 2024-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITE", "WAITE"),
                    ("DONE", "DONE"),
                    ("پذیرش شده", "پذیرش شده"),
                    ("عدم مراجعه", "عدم مراجعه"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="packageappointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITE", "WAITE"),
                    ("DONE", "DONE"),
                    ("پذیرش شده", "پذیرش شده"),
                    ("عدم مراجعه", "عدم مراجعه"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
