# Generated by Django 5.0 on 2024-05-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
