# Generated by Django 5.0 on 2024-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="is_holiday",
            field=models.BooleanField(default=False),
        ),
    ]
