# Generated by Django 5.0 on 2024-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_day_is_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="national_id",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
