# Generated by Django 5.0 on 2024-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_session_name_session_national_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="national_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
