# Generated by Django 5.0 on 2024-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_alter_session_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="name",
        ),
        migrations.AddField(
            model_name="session",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
