# Generated by Django 5.0 on 2024-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_day_created_at_day_created_by_day_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("در انتظار", "در انتظار"),
                    ("پذیرش شده", "پذیرش شده"),
                    ("عدم مراجعه", "عدم مراجعه"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
