# Generated by Django 5.0 on 2024-05-05 15:28

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_session_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
