# Generated by Django 5.0 on 2024-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_day_mock_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deletedsession",
            name="reason",
        ),
        migrations.AddField(
            model_name="deletedsession",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("در انتظار", "در انتظار"),
                    ("پذیرش شده", "پذیرش شده"),
                    ("عدم مراجعه", "عدم مراجعه"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
