# Generated by Django 5.0 on 2024-05-08 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0014_remove_deletedsession_status_deletedsession_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="christ_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
