# Generated by Django 4.2.10 on 2024-03-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0013_alter_client_case_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_number", models.CharField(max_length=20)),
                ("receiver_number", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=255)),
                ("message_body", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
            ],
        ),
    ]
