# Generated by Django 4.2.10 on 2024-02-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0006_remove_reception_prescription"),
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="reception",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="reception.reception"
            ),
        ),
    ]
