# Generated by Django 4.2.10 on 2024-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_alter_financial_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="consumable_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financial",
            name="service_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
