# Generated by Django 4.2.10 on 2024-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_financial_consumable_price_financial_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="valid_insurance",
            field=models.BooleanField(default=False),
        ),
    ]
