# Generated by Django 4.2.10 on 2024-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0004_financial_valid_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="insurance_range",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
