# Generated by Django 4.2.10 on 2024-02-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0006_financial_insurance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="final_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
