# Generated by Django 4.2.10 on 2024-03-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0008_financial_created_at_financial_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "پرداخت شده"),
                    ("UNPAID", "پرداخت نشده"),
                    ("PARTIAL", "اقساط"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
