# Generated by Django 4.2.10 on 2024-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0011_alter_financial_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partial Payment"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
