# Generated by Django 4.2.10 on 2024-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0013_officeexpenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeexpenses",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
