# Generated by Django 4.2.10 on 2024-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0016_remove_officeexpenses_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="tax",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
