# Generated by Django 4.2.10 on 2024-03-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0019_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="percentage",
        ),
    ]
