# Generated by Django 4.2.10 on 2024-03-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0021_alter_coupon_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
