# Generated by Django 4.2.10 on 2024-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0022_delete_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
            ],
        ),
    ]
