# Generated by Django 4.2.10 on 2024-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0027_financial_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="doctors_wage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="financial",
            name="revenue",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
