# Generated by Django 5.0 on 2024-04-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0030_remove_financial_consumable_price_consumableprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumableprice",
            name="invoice",
        ),
    ]
