# Generated by Django 5.0 on 2024-04-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0032_alter_consumableprice_reception"),
        ("reception", "0014_alter_reception_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumableprice",
            name="reception",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reception.reception"
            ),
        ),
    ]
