# Generated by Django 5.0 on 2024-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0033_alter_consumableprice_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumableprice",
            name="dose",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
