# Generated by Django 5.0 on 2024-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0034_consumableprice_dose"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="consumable_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
