# Generated by Django 5.0 on 2024-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0036_remove_financial_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("پرداخت شده", "پرداخت شده"),
                    ("پرداخت نشده", "پرداخت نشده"),
                    ("قسط یندی", "قسط یندی"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
