# Generated by Django 5.0 on 2024-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0039_alter_financial_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officeexpenses",
            name="date",
            field=models.CharField(max_length=255),
        ),
    ]
