# Generated by Django 5.0 on 2024-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0040_alter_officeexpenses_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="jalali_date_issued",
            field=models.CharField(default="this", max_length=255),
            preserve_default=False,
        ),
    ]
