# Generated by Django 5.0 on 2024-04-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_assign_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reopen_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
