# Generated by Django 4.2.10 on 2024-02-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_consumablecategory_alter_consumable_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
