# Generated by Django 4.2.10 on 2024-02-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumable",
            name="supplier",
        ),
    ]
