# Generated by Django 4.2.10 on 2024-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0005_consumable_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="inventory_tracking_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
