# Generated by Django 4.2.10 on 2024-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0006_consumable_inventory_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
