# Generated by Django 4.2.10 on 2024-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0007_consumable_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("acquisition_date", models.DateField()),
                ("warranty_expiry_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
