# Generated by Django 4.2.10 on 2024-03-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0008_medicalequipment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MedicalEquipment",
            new_name="Equipment",
        ),
    ]
