# Generated by Django 5.0 on 2024-04-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0014_consumable_reoder_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumable",
            old_name="reoder_quantity",
            new_name="reorder_quantity",
        ),
    ]
