# Generated by Django 5.0 on 2024-04-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0016_consumable_expiration_reminder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumablecategory",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Consumable",
        ),
        migrations.DeleteModel(
            name="ConsumableCategory",
        ),
    ]
