# Generated by Django 5.0 on 2024-04-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0017_remove_consumablecategory_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
