# Generated by Django 5.0 on 2024-05-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0023_equipment_is_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="is_user",
            new_name="is_use",
        ),
    ]
