# Generated by Django 4.2.13 on 2024-05-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0024_rename_is_user_equipment_is_use"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="is_use",
            new_name="in_use",
        ),
    ]
