# Generated by Django 4.2.10 on 2024-02-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
