# Generated by Django 4.2.10 on 2024-02-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("reception", "0003_reception_created_at_reception_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
            ),
        ),
    ]
