# Generated by Django 4.2.10 on 2024-02-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0005_reception_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reception",
            name="prescription",
        ),
    ]
