# Generated by Django 4.2.10 on 2024-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0006_remove_reception_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
