# Generated by Django 4.2.10 on 2024-03-10 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0007_alter_reception_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reception",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
