# Generated by Django 4.2.10 on 2024-03-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0008_reception_date_alter_reception_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reception",
            name="date",
        ),
    ]
