# Generated by Django 4.2.10 on 2024-03-12 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0009_remove_reception_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
