# Generated by Django 4.2.10 on 2024-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0010_reception_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="reception_in_day",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
