# Generated by Django 4.2.10 on 2024-03-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0011_reception_reception_in_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="invoice_attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
