# Generated by Django 5.0 on 2024-04-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_appointment_client_name_and_more"),
        ("reception", "0012_reception_invoice_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.appointment",
            ),
        ),
    ]
