# Generated by Django 5.0 on 2024-04-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_alter_appointment_status_and_more"),
        ("reception", "0013_reception_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.appointment",
            ),
        ),
    ]
