# Generated by Django 5.0 on 2024-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0015_alter_reception_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="payment_status",
            field=models.CharField(
                choices=[("پرداخت شده", "پرداخت شده"), ("پرداخت نشده", "پرداخت نشده")],
                max_length=100,
            ),
        ),
    ]
