# Generated by Django 5.0 on 2024-05-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_session_status"),
        ("reception", "0016_alter_reception_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planner.session",
            ),
        ),
    ]
