# Generated by Django 5.0 on 2024-05-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0017_reception_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reception",
            name="appointment",
        ),
    ]
