# Generated by Django 5.0 on 2024-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0018_remove_reception_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="date",
            field=models.CharField(max_length=255),
        ),
    ]
