# Generated by Django 5.0 on 2024-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0019_alter_reception_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
