# Generated by Django 5.0 on 2024-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0020_alter_reception_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="date",
            field=models.CharField(max_length=255),
        ),
    ]
