# Generated by Django 5.0 on 2024-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0021_alter_reception_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="jalali_date",
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reception",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
