# Generated by Django 5.0 on 2024-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("در انبار", "در انبار"),
                    ("تمام شده", "تمام شده"),
                    ("سفارش داده شده", "سفارش داده شده"),
                    ("منقضی شده", "منقضی شده"),
                ],
                default="در انبار",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
