# Generated by Django 5.0 on 2024-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0003_consumablev2_reorder_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumablev2",
            name="expiration_reminder",
        ),
        migrations.AddField(
            model_name="inventory",
            name="expiration_reminder",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
