# Generated by Django 5.0 on 2024-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0004_remove_consumablev2_expiration_reminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumablev2",
            name="expiration_reminder",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
