# Generated by Django 5.0 on 2024-04-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0005_consumablev2_expiration_reminder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumablev2",
            name="expiration_reminder",
        ),
    ]
