# Generated by Django 5.0 on 2024-04-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0008_alter_consumablev2_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumablev2",
            name="category",
        ),
    ]
