# Generated by Django 5.0 on 2024-04-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0009_remove_consumablev2_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumablev2",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consumable.consumablecategory",
            ),
        ),
    ]
