# Generated by Django 5.0 on 2024-04-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0011_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumablev2",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consumable.supplier",
            ),
        ),
    ]
