# Generated by Django 5.0 on 2024-04-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0013_remove_consumablev2_inventory_tracking_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumablev2",
            name="supplier",
        ),
    ]
