# Generated by Django 5.0 on 2024-04-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0014_remove_consumablev2_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consumable.supplier",
            ),
        ),
    ]
