# Generated by Django 5.0 on 2024-04-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0015_alter_inventory_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumablev2",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumables",
                to="consumable.consumablecategory",
            ),
        ),
    ]
