# Generated by Django 5.0 on 2024-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumable", "0016_alter_consumablev2_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="purchase_date",
            field=models.CharField(max_length=255),
        ),
    ]
