# Generated by Django 4.2.10 on 2024-02-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
        ("client", "0003_client_created_at_client_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance.insurance",
            ),
        ),
    ]
