# Generated by Django 4.2.10 on 2024-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
