# Generated by Django 4.2.10 on 2024-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_client_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images"
            ),
        ),
    ]
