# Generated by Django 4.2.10 on 2024-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_rename_number_of_reception_client_number_of_receptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_reception_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
