# Generated by Django 4.2.10 on 2024-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_client_last_reception_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_reception_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
