# Generated by Django 4.2.10 on 2024-03-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_client_last_reception_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="number_of_receptions",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
