# Generated by Django 4.2.10 on 2024-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_alter_client_number_of_receptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="case_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
