# Generated by Django 5.0 on 2024-05-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_case_id"),
        ("planner", "0007_remove_session_name_session_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="initial_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initial_session",
                to="planner.session",
            ),
        ),
    ]
