# Generated by Django 5.0 on 2024-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0017_clientattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientattachment",
            name="type",
            field=models.CharField(default="this", max_length=255),
            preserve_default=False,
        ),
    ]
