# Generated by Django 5.0 on 2024-05-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0018_clientattachment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientattachment",
            name="description",
        ),
    ]
