# Generated by Django 5.0 on 2024-05-13 09:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0019_remove_clientattachment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
