# Generated by Django 5.0 on 2024-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0020_alter_client_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=models.CharField(max_length=255),
        ),
    ]
