# Generated by Django 4.2.13 on 2024-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0021_alter_client_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="high_risk",
            field=models.CharField(
                blank=True,
                choices=[("C", "C"), ("B", "B"), ("A", "A")],
                max_length=255,
                null=True,
            ),
        ),
    ]
