# Generated by Django 4.2.13 on 2024-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0022_client_high_risk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="high_risk",
            field=models.CharField(
                blank=True,
                choices=[("B", "B"), ("A", "A"), ("C", "C")],
                max_length=255,
                null=True,
            ),
        ),
    ]
