# Generated by Django 4.2.10 on 2024-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("policy_number", models.CharField(max_length=50)),
                ("insurance_company", models.CharField(max_length=100)),
                ("deductible", models.DecimalField(decimal_places=2, max_digits=10)),
                ("copay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_annual_coverage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("policy_type", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
