# Generated by Django 5.0 on 2024-05-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0004_insuranceservice_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurance",
            options={"permissions": [("insurance", "Can view insurance")]},
        ),
    ]
