# Generated by Django 5.0 on 2024-05-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0005_alter_insurance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurance",
            options={},
        ),
    ]
